### ISSUE TITLE
Entity to export packing slip data

### ISSUE THREAD

**Issue by FH-Inway** [NathanClouseAX/AAXDataEntities#11]
Hey @NathanClouseAX , inspired by a recent [Yammer discussion](https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1338643063119872), I wanted to give this a try :)

**Is your feature request related to a problem? Please describe.**
The standard application provides no entity to export packing slip data, which is needed to provide a shipping company with an electronic version of a packing slip.

**Describe the solution you'd like**
A composite entity consisting at least of the most relevant data in the packing slip header and line tables. "Nice to have" would be additional data from those and other related tables (e.g. tracking information, external item numbers, ...). The entity only needs to support data export.

**Describe alternatives you've considered**
- Looked at standard entities that are somewhat packing slip related (BusinessDocument*PackingSlipLine entities or SalesPackingSlipTrackingInformation), but they don't contain all the necessary information.
- Export to Excel from the packing slip journal form is a manual alternative that requires quite some work if several packing slips are to be exported and cannot be easily automated.
- Electronic reporting could maybe be used to configure something without development, but it would probably just as much or even more effort. The Microsoft repository does not seem to contain an ER data model for packing slips out-of-the-box. An entity might also help in creating one.

**Additional context**
None at the moment.

**Comment by NathanClouseAX** [comment]
Sounds good. I'll write entities for Packing Slip Headers and also lines to support a simple DMF export as well as make them OData entities incase someone wants to pull this up in Excel. This could also support a Power BI story around packing slip volume or other telemetry. We can review the data from those entities and use those as the basis for a composite entity.

Since the primary consumer for the use case will be a third party shipper, are there any specific internationalization requirements that we should call out that may not be standard in USA? Harmonized Codes or Trade zone codes, for instance.

**Comment by FH-Inway** [comment]
Sounds good, didn't even think about Power BI.

Not sure about your question though, my background is more technical than functional consultant. But I let the people in the Yammer discussion know about this, maybe they can provide some input.

**Comment by NathanClouseAX** [comment]
Just as a call out, data entities "Customer packing slip lines - invoiced", "Customer packing slip lines - non stocked", and "Customer packing slip lines - stocked" may work for some without the need for any extra data entities. These do have implicit filters. The first being on the underlying product stocking type and the second on invoice status. The entities that will be provided in the following commit will show customer packing slips headers and line with no additional filters. If it exists, it will be visible with the entities added in this repo.

**Customer packing slip lines - stocked;** Only shows packing slip lines that have been invoiced for products which are also stocked
**Customer packing slip lines - non stocked;** only shows packing slip lines that have been invoiced for products which are not stocked
**Customer packing slip lines - invoiced;** only shows packing slip lines that have been invoiced

**Comment by NathanClouseAX** [comment]
Closing issue with 11d91fe36da38c7835e0ce1a564559d1241be488. They've passed initial testing in 10.0.17 and are ready for a larger audience.

**Comment by FH-Inway** [comment]
I took the new entities for a spin on my PEAP 10.0.21 machine with Contoso demo data. It compiled and synchronized without a problem. I tested the entities with export data projects.

The export project with the composite entity created an xml file which only contains the header records data, the line data is missing.

I created another export project with just the lines entity. During setup, I got a message "Entity 'Customer packing slip lines' doesn't have primary or unique key. Staging table 'AAXCustomerPackingSlipJournalLinesStaging' needs to be altered. The export finished with execution status "Partially succeeded". The staging data contains one record and the execution log for the source stage contains many messages of the pattern "Cannot create a record in Accountants (AAXCustomerPackingSlipJournalLinesStaging)". Item: L0001, Mid-Range Speaker 2. The record already exists."

![image](https://user-images.githubusercontent.com/33372796/131130807-306c2e96-af07-4d68-88ae-7cfd7158bcb3.png)
![image](https://user-images.githubusercontent.com/33372796/131130891-867f201c-5d95-4b80-9e7f-e4b4498f1270.png)

**Comment by NathanClouseAX** [comment]
I'll review this weekend and get back to you. Thanks for testing!

**Comment by FH-Inway** [comment]
I also noticed that the header data contains RecIds for the adresses. Since the natural adress data is important for a packing slip, it would be nice if the adress data could be included in the entity.

**Comment by NathanClouseAX** [comment]
I was unable to replicate the specific error you had in .21. I did experience a different error after extended testing in .17 with the composite entity so I will be resolving that then continuing testing with .21. Addressing and Inventory dimension info has been added where available plus misc. renames on fields to match OOTB entities. more to come.

**Comment by FH-Inway** [comment]
I gave this another go with the latest changes on a PEAP .22 machine (upgraded from the previously used .21 machine). Got the warning about the missing unique index again during setup of the data projects.
In addition, I got the following warning message during setup: "Customer Packing Slip header and Lines_AAXCustomerPackingSlipJournalLinesEntity entity has disabled field(s): field ITEMCODEID is disabled by config key SysDeletedObjects72. Please remove the field(s) in the mapping or enable the respective config key(s)"

:x: Export of the composite entity seems to get stuck in an endless export. The staging data gets filled ok, but it seems to be stuck creating the export file.
:heavy_check_mark: Export of the packing slip headers worked. Adressing information looks good.
:x: Export of the packing slip lines resulted in an error "Results. Record ('') . The value "AAXCustomerPackingSlipJournalLinesEntity" is not found in the map."

I will try again when the new 10.0.21 VHD gets released so I can test on a clean environment.

![image](https://user-images.githubusercontent.com/33372796/133930302-2ceaa85d-08e1-4a95-9651-d62c9ff053af.png)

**Comment by NathanClouseAX** [comment]
After the last commit, I built everything from scratch on a new .21 VM. I am getting an error related to key types that I'll attempt to resolve tomorrow.

![image](https://user-images.githubusercontent.com/30779047/134793610-41c443dc-6e19-4f68-a088-7b264b1cca17.png)

**Comment by NathanClouseAX** [comment]
This should be resolved by the latest commit. I was able to create and export a data package for the composite data entity. Please get latest, build, sync, and let me know if you run into any issues. Thanks!

**Comment by FH-Inway** [comment]
That version works for me, too. Good work!
